"""Add non-nullable and unique constraints to SymbolCategory and Symbol, also User model

Revision ID: 405ac63c54b5
Revises: 
Create Date: 2024-09-11 11:39:29.339731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405ac63c54b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
