"""add `username` column in `user` table

Revision ID: eee6cc0f54c4
Revises: 405ac63c54b5
Create Date: 2024-09-12 20:32:13.658466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee6cc0f54c4'
down_revision = '405ac63c54b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=False))
        batch_op.create_unique_constraint("uq_user_username", ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_username", type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
